Update CI-pipeline.yml

diff --git a/.github/workflows/CI-pipeline.yml b/.github/workflows/CI-pipeline.yml
--- a/.github/workflows/CI-pipeline.yml
+++ b/.github/workflows/CI-pipeline.yml
@@ -36,46 +36,59 @@ jobs:
 
     - name: Run Unit Tests
       run: |
-        dotnet test ${{env.UNIT_TEST_PROJECT}} --verbosity normal --no-restore --collect:"XPlat Code Coverage" --logger trx
+        dotnet test ${{env.UNIT_TEST_PROJECT}} --configuration ${{env.BUILD_CONFIG}} --no-restore --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory TestResults --logger trx
         echo "Unit tests completed successfully"
+        
+    - name: Upload dotnet test results
+      uses: actions/upload-artifact@v3
+      with:
+          name: test-results
+          path: TestResults
+      # Use always() to always run this step to publish test results when there are test failures
+      if: ${{ always() }}
+    - name: Publish Test Results to PR
+      uses: EnricoMi/publish-unit-test-result-action@v2
+      if: always()
+      with:
+        files: |
+          TestResults/*.trx
+
+    - name: View Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()
+      with:
+        name: View Unit Tests
+        path: TestResults/*.trx
+        reporter: dotnet-trx
     
-    ##- name: Generate coverage report
-      ##run: |
-          ##reportgenerator "-reports:$(find . -name '*.coverage')" "-targetdir:coverage" "-reporttypes:Html"
     - name: Install ReportGenerator
       run: |
         dotnet tool install -g dotnet-reportgenerator-globaltool
-    
-    - name: Generate coverage report
+    ## TestResults
+    - name: Generate detailed coverage report
       run: |
         reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverage"
           
-    - name: Upload coverage report
+    - name: Upload detailed coverage report
       uses: actions/upload-artifact@v2
       with:
         name: Coverage Report
         path: coverage
     
-    - name: Publish coverage report as GitHub Pages
+    - name: Publish detailed coverage report as GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./coverage
-        
-    - name: Publish code coverage report
-      uses: actions/upload-artifact@v2
-      with:
-        name: code-coverage
-        path: coverage
 
-    - name: Test2
-      run: |
-        dotnet test ${{env.UNIT_TEST_PROJECT}} --configuration ${{env.BUILD_CONFIG}} --no-restore --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage2
+    ##- name: Test2
+    ##  run: |
+    ##    dotnet test ${{env.UNIT_TEST_PROJECT}} --configuration ${{env.BUILD_CONFIG}} --no-restore --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage2
 
     - name: Code Coverage Report
       uses: irongut/CodeCoverageSummary@v1.3.0
       with:
-        filename: coverage2/**/coverage.cobertura.xml
+        filename: TestResults/**/coverage.cobertura.xml
         badge: true
         fail_below_min: true
         format: markdown
@@ -92,20 +105,4 @@ jobs:
         recreate: true
         path: code-coverage-results.md
   
-  coverage:
-    needs: build-and-test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Download code coverage report
-        uses: actions/download-artifact@v2
-        with:
-          name: code-coverage
-
-      - name: Publish code coverage
-        uses: codecov/codecov-action@v1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
     
